### ISSUE TITLE
Creating file nodes.

### ISSUE THREAD

**Issue by bjorns** [TWCable/jackalope#5]
Hi, I'm trying jackalope out. Seems very promising but I'm stuck trying to create a file node. I have something like this but it doesn't seem to work properly. Any tips?

```
    node('config.xml',
            property(JcrConstants.JCR_PRIMARYTYPE, JcrConstants.NT_FILE),
            node('jcr:content',
                    property(JcrConstants.JCR_PRIMARYTYPE, JcrConstants.NT_RESOURCE),
                    property(JcrConstants.JCR_DATA, getClass().getResourceAsStream("config.xml")))))
```

I was looking into the resource() builder function but I can't get it to play with the rest of the jcrbuilder code in the same file.

**Comment by hsfear** [comment]
We've seem to have done this a couple of ways depending on the need.

``` groovy
node("filename", NT_FILE,
    node("jcr:content", property("jcr:data", content)
)
```

and

``` groovy
node("filename",
    property(JCR_PRIMARYTYPE, "nt:file"),
    node("jcr:content",
        property("jcr:data", new ValueFactoryImpl().createBinary(inputStream(content)))))
```

**Comment by bjorns** [comment]
Cool, the second one seems to be what I need. Let me try.

**Comment by bjorns** [comment]
Yep, seems to work, thanks!
